version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: pe_mysql
    volumes:
      - ./bin/mysql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: pe_wordpress
    depends_on:
      - mysql
    image: hardeepasrani/pirate-brewery
    networks:
      - default
    ports:
      - 80:80
    volumes:
       - ./wp-content:/var/www/html/wp-content/
       - .:/var/www/html/wp-content/plugins/post-expirator/
       - ./bin/:/var/www/html/pe-bin/
       - ./test/:/var/www/html/pe-test/
    restart: always
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_ROOT_PASSWORD: wordpress

