version: '3.1'

services:
  wordpress:
    image: wordpress:5.6-php7.4
    restart: always
    ports:
      - 9080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: wordpress
      ABSPATH: /usr/src/wordpress/
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SCRIPT_DEBUG', true );
    volumes:
      - wordpress_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/post-expirator/
      - ./test/:/var/www/html/pe-test/
      - ./bin/:/var/www/html/pe-bin/
    depends_on:
      - mysql

  cli:
    image: wordpress:cli
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/post-expirator/
    depends_on:
      - mysql
      - wordpress
    command: tail -f /dev/null

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 9306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress

volumes:
  wordpress_data: